### ISSUE TITLE
Dart

### ISSUE THREAD

**Issue by Thihup** [lastmjs/zwitterion#241]
Add Dart support would be great.

**Comment by lastmjs** [comment]
I'm not sure I want to support Dart in Zwitterion core for multiple reasons, mostly dealing with popularity and Dart's future as a language. But, I am considering creating plugin capabilities where users could create their own plugins for languages that they want supported that Zwitterion core will not support: https://github.com/lastmjs/zwitterion/issues/119

Do you have thoughts on this @Thihup ?

**Comment by Thihup** [comment]
Sounds good to me
