### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by clmay** [lastmjs/zwitterion#286]
It would be great to have the examples you demoed at your talk tonight easily available. Maybe `/examples` here, or a `zwitterion-examples` repo?

**Comment by lastmjs** [comment]
Done: https://github.com/lastmjs/zwitterion/tree/master/examples

**Comment by lastmjs** [comment]
Let me know of if you need more!

**Comment by clmay** [comment]
That's great! Thank you!
