### ISSUE TITLE
Deno vs Zwitterion

### ISSUE THREAD

**Issue by JerryGreen** [lastmjs/zwitterion#325]
Pls someone write some detailed comparison of them both with why would one choose Zwitterion over Deno (which has kinda the same functionality, but is also maintained by author of NodeJS, Ryan Dahl, - so at least some hype comes out of the box 😂)

Which pros? Which cons?

**Comment by lastmjs** [comment]
Hi!

Zwitterion and Deno are pretty different projects. Deno is a JavaScript/TypeScript runtime or platform, very similar to Node.js. It is designed to allow you to run JavaScript/TypeScript outside of the browser, giving you access to OS APIs and other APIs not found in a browser environment.

Zwitterion is very different from Node.js or Deno. It is not designed to allow you to run JavaScript/TypeScript outside of the browser, but inside of the browser. It is very similar to Webpack or Parcel, but is not a bundler. You can start up a Zwitterion server in your web project and then access it through localhost like any other static file server. It will automatically transpile your JavaScript, TypeScript, and some other languages as they are served to the browser. It's supposed to be much simpler than using something like Webpack or Parcel.

Let me know if you have anymore questions

**Comment by jerrygreen** [comment]
I just saw an [example](https://github.com/lastmjs/zwitterion/tree/master/examples/basic) and it actually looks cool, and now I understand that it builds static files and excludes the server part in production build, and everything you told suddenly makes sense actually! Thx for explaining
