### ISSUE TITLE
An import path cannot end with a ".ts" extension

### ISSUE THREAD

**Issue by jerrygreen** [lastmjs/zwitterion#332]
![image](https://user-images.githubusercontent.com/13215662/109412981-e78d0480-79cc-11eb-8fda-46bdb50e914b.png)

While the code above actually works, it sill provides poor feedback from VSCode.

There were a similar problem in Deno:

https://stackoverflow.com/questions/65115527/how-can-i-avoid-the-an-import-path-cannot-end-with-ts-extension-error-in-vsco

They made a whole separate extension to suppress that (which brings other cool features like linting, etc.)

In webpack they solve it somehow too (but configuring it is a mess ofc, - would be cool that be supported out of the box):

https://stackoverflow.com/questions/40616272/an-import-path-cannot-end-with-ts-nodejs-and-visual-code/49970851

Ideally it should be somehow dealt with, otherwise it's a poor developer experience (or user experience? assuming that by users I mean Zwitterion users 😂)

**Comment by lastmjs** [comment]
Yeah, it's an annoying error. Just drop the extension and you should be
good to go

**Comment by jerrygreen** [comment]
Huh, I actually thought it is required, not an optional thing. But cool then
