### ISSUE TITLE
Prepare for widespread transpilation

### ISSUE THREAD

**Issue by lastmjs** [lastmjs/zwitterion#69]
I'm thinking that Zwitterion will be able to do transpilation of many different languages in the future. For example, my dream is that Zwitterion is able to allow the user to mashup web components and other scripts written in a variety of languages, including C/C++, Rust, Haskell, PureScript, WebAssembly, etc. Right now we are only allowing TypeScript to be transpiled, but we could easily allow files with other extensions to be transpiled. C/C++ and Rust could be transpiled to WebAssembly...Haskell potentially as well. Some languages we already have the tools for...the point is, think about it, and begin to design the server to support the transpilation and serving of various languages.

**Comment by idibidiart** [comment]
I'd focus on adding Rust for now, until WASM support for high level languages is there

https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md

**Comment by lastmjs** [comment]
Agreed, I'm going to start with C/C++ and WASM though, Rust should follow easily after that. I've got the basics working, ES module integration will be the trickiest

**Comment by lastmjs** [comment]
This is coming along very well, the structure is in place to easily support arbitrary extensions, and I've had some good experience experimenting with WASM.

**Comment by lastmjs** [comment]
AssemblyScript and Rust should be coming shortly, in the middle of a refactor that implements this
