### ISSUE TITLE
File Importing?

### ISSUE THREAD

**Issue by dansteren** [lastmjs/zwitterion#90]
I'm a little confused as to how file importing is supposed to work. I have my code setup in the following three files:

~/index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <script src="node_modules/react/dist/react.min.js"></script>
    <script src="node_modules/react-dom/dist/react-dom.min.js"></script>
  </head>
  <body>
    <app />
    <script src="./components/TextTag.tsx"></script>
    <script src="app.tsx"></script>
  </body>
</html>
```
~/App.tsx
```tsx
import TextTag from './components/TextTag';

class App extends React.Component {
  render() {
    return (
      <div>
        String from App component
         <TextTag />
      </div>
    );
  }
}

ReactDOM.render(
  <App />,
  document.querySelector('app')
);
```
~/components/TextTag.tsx
```tsx
class TextTag extends React.Component {
  render() {
    return (
      <div>
        String from TextTag
      </div>
    );
  }
}

export default TextTag;
```

Although this seems perfectly normal to me it doesn't work. However if I put the contents of TextTag directly into App.tsx as shown below, it works just fine.
```tsx
class TextTag extends React.Component {
  render() {
    return (
      <div>
        String from TextTag
      </div>
    );
  }
}

class App extends React.Component {
  render() {
    return (
      <div>
        String from App component
         <TextTag />
      </div>
    );
  }
}

ReactDOM.render(
  <App />,
  document.querySelector('app')
);
```
The only way I know how to compose components is using the format I've shown in my files above. That seems to be the standard way of importing files and would be familiar to most React developers. Switching to zwitterion I'm not sure to actually make this work.

What is the correct way to compose components when developing with zwitterion?

**Comment by lastmjs** [comment]
Everything should work exactly the same way, just make sure to use `type="module"` on your script tags if you're including an ES module: https://github.com/lastmjs/zwitterion#es-modules

The `type="module"` on script tags is the standard syntax for including ES modules, and will be adopted in all major browsers. Zwitterion uses that syntax now

**Comment by lastmjs** [comment]
Also, you might want to get rid of the `./` in `<script src="./components/TextTag.tsx"></script>`

**Comment by lastmjs** [comment]
You don't need it, and I don't think it's standard for relative paths

**Comment by lastmjs** [comment]
If you have anymore questions let me know
